/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AiUstadzRouteImport } from './routes/ai-ustadz'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTasbihRouteImport } from './routes/_app/tasbih'
import { Route as AppSosialRouteImport } from './routes/_app/sosial'
import { Route as AppProfilRouteImport } from './routes/_app/profil'
import { Route as AppIlmuRouteImport } from './routes/_app/ilmu'
import { Route as AppIbadahRouteImport } from './routes/_app/ibadah'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppQuranIndexRouteImport } from './routes/_app/quran.index'
import { Route as AppQuranSurahIdRouteImport } from './routes/_app/quran.$surahId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AiUstadzRoute = AiUstadzRouteImport.update({
  id: '/ai-ustadz',
  path: '/ai-ustadz',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasbihRoute = AppTasbihRouteImport.update({
  id: '/tasbih',
  path: '/tasbih',
  getParentRoute: () => AppRoute,
} as any)
const AppSosialRoute = AppSosialRouteImport.update({
  id: '/sosial',
  path: '/sosial',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const AppIlmuRoute = AppIlmuRouteImport.update({
  id: '/ilmu',
  path: '/ilmu',
  getParentRoute: () => AppRoute,
} as any)
const AppIbadahRoute = AppIbadahRouteImport.update({
  id: '/ibadah',
  path: '/ibadah',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppQuranIndexRoute = AppQuranIndexRouteImport.update({
  id: '/quran/',
  path: '/quran/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuranSurahIdRoute = AppQuranSurahIdRouteImport.update({
  id: '/quran/$surahId',
  path: '/quran/$surahId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-ustadz': typeof AiUstadzRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/home': typeof AppHomeRoute
  '/ibadah': typeof AppIbadahRoute
  '/ilmu': typeof AppIlmuRoute
  '/profil': typeof AppProfilRoute
  '/sosial': typeof AppSosialRoute
  '/tasbih': typeof AppTasbihRoute
  '/quran/$surahId': typeof AppQuranSurahIdRoute
  '/quran/': typeof AppQuranIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-ustadz': typeof AiUstadzRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/home': typeof AppHomeRoute
  '/ibadah': typeof AppIbadahRoute
  '/ilmu': typeof AppIlmuRoute
  '/profil': typeof AppProfilRoute
  '/sosial': typeof AppSosialRoute
  '/tasbih': typeof AppTasbihRoute
  '/quran/$surahId': typeof AppQuranSurahIdRoute
  '/quran': typeof AppQuranIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/ai-ustadz': typeof AiUstadzRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/ibadah': typeof AppIbadahRoute
  '/_app/ilmu': typeof AppIlmuRoute
  '/_app/profil': typeof AppProfilRoute
  '/_app/sosial': typeof AppSosialRoute
  '/_app/tasbih': typeof AppTasbihRoute
  '/_app/quran/$surahId': typeof AppQuranSurahIdRoute
  '/_app/quran/': typeof AppQuranIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-ustadz'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/home'
    | '/ibadah'
    | '/ilmu'
    | '/profil'
    | '/sosial'
    | '/tasbih'
    | '/quran/$surahId'
    | '/quran/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-ustadz'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/home'
    | '/ibadah'
    | '/ilmu'
    | '/profil'
    | '/sosial'
    | '/tasbih'
    | '/quran/$surahId'
    | '/quran'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/ai-ustadz'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/_app/home'
    | '/_app/ibadah'
    | '/_app/ilmu'
    | '/_app/profil'
    | '/_app/sosial'
    | '/_app/tasbih'
    | '/_app/quran/$surahId'
    | '/_app/quran/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AiUstadzRoute: typeof AiUstadzRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-ustadz': {
      id: '/ai-ustadz'
      path: '/ai-ustadz'
      fullPath: '/ai-ustadz'
      preLoaderRoute: typeof AiUstadzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tasbih': {
      id: '/_app/tasbih'
      path: '/tasbih'
      fullPath: '/tasbih'
      preLoaderRoute: typeof AppTasbihRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sosial': {
      id: '/_app/sosial'
      path: '/sosial'
      fullPath: '/sosial'
      preLoaderRoute: typeof AppSosialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil': {
      id: '/_app/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ilmu': {
      id: '/_app/ilmu'
      path: '/ilmu'
      fullPath: '/ilmu'
      preLoaderRoute: typeof AppIlmuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ibadah': {
      id: '/_app/ibadah'
      path: '/ibadah'
      fullPath: '/ibadah'
      preLoaderRoute: typeof AppIbadahRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quran/': {
      id: '/_app/quran/'
      path: '/quran'
      fullPath: '/quran/'
      preLoaderRoute: typeof AppQuranIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quran/$surahId': {
      id: '/_app/quran/$surahId'
      path: '/quran/$surahId'
      fullPath: '/quran/$surahId'
      preLoaderRoute: typeof AppQuranSurahIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppIbadahRoute: typeof AppIbadahRoute
  AppIlmuRoute: typeof AppIlmuRoute
  AppProfilRoute: typeof AppProfilRoute
  AppSosialRoute: typeof AppSosialRoute
  AppTasbihRoute: typeof AppTasbihRoute
  AppQuranSurahIdRoute: typeof AppQuranSurahIdRoute
  AppQuranIndexRoute: typeof AppQuranIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppIbadahRoute: AppIbadahRoute,
  AppIlmuRoute: AppIlmuRoute,
  AppProfilRoute: AppProfilRoute,
  AppSosialRoute: AppSosialRoute,
  AppTasbihRoute: AppTasbihRoute,
  AppQuranSurahIdRoute: AppQuranSurahIdRoute,
  AppQuranIndexRoute: AppQuranIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AiUstadzRoute: AiUstadzRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
